export { authRouter } from './auth.routes';
export { propertiesRouter } from './properties.routes';
export { certificatesRouter } from './certificates.routes';
export { remedialRouter } from './remedial.routes';
export { contractorsRouter } from './contractors.routes';
export { adminRouter } from './admin.routes';
export { systemRouter } from './system.routes';
export { configRouter } from './config.routes';
export { reportsRouter } from './reports.routes';
export { extractionRouter } from './extraction.routes';
export { geoRouter } from './geo.routes';
export { analyticsRouter } from './analytics.routes';
export { default as observabilityRoutes } from './observability.routes';
