import type { IStorage } from "./interfaces";
import { usersStorage, UsersStorage } from "./domains/users.storage";
import { propertiesStorage, PropertiesStorage } from "./domains/properties.storage";
import { certificatesStorage, CertificatesStorage } from "./domains/certificates.storage";
import { remedialsStorage, RemedialsStorage } from "./domains/remedials.storage";
import { contractorsStorage, ContractorsStorage } from "./domains/contractors.storage";
import { configurationStorage, ConfigurationStorage } from "./domains/configuration.storage";
import { componentsStorage, ComponentsStorage } from "./domains/components.storage";
import { apiStorage, ApiStorage } from "./domains/api.storage";
import { systemStorage, SystemStorage } from "./domains/system.storage";

export class DatabaseStorage implements IStorage {
  private users = usersStorage;
  private properties = propertiesStorage;
  private certificates = certificatesStorage;
  private remedials = remedialsStorage;
  private contractors = contractorsStorage;
  private configuration = configurationStorage;
  private components = componentsStorage;
  private api = apiStorage;
  private system = systemStorage;

  getUser = this.users.getUser.bind(this.users);
  getUserByUsername = this.users.getUserByUsername.bind(this.users);
  createUser = this.users.createUser.bind(this.users);
  listUsers = this.users.listUsers.bind(this.users);
  updateUserRole = this.users.updateUserRole.bind(this.users);
  getSuperAdmin = this.users.getSuperAdmin.bind(this.users);

  getOrganisation = this.properties.getOrganisation.bind(this.properties);
  createOrganisation = this.properties.createOrganisation.bind(this.properties);
  listOrganisations = this.properties.listOrganisations.bind(this.properties);
  updateOrganisation = this.properties.updateOrganisation.bind(this.properties);
  deleteOrganisation = this.properties.deleteOrganisation.bind(this.properties);
  getHierarchyStats = this.properties.getHierarchyStats.bind(this.properties);
  listSchemes = this.properties.listSchemes.bind(this.properties);
  getScheme = this.properties.getScheme.bind(this.properties);
  createScheme = this.properties.createScheme.bind(this.properties);
  updateScheme = this.properties.updateScheme.bind(this.properties);
  deleteScheme = this.properties.deleteScheme.bind(this.properties);
  listBlocks = this.properties.listBlocks.bind(this.properties);
  getBlock = this.properties.getBlock.bind(this.properties);
  createBlock = this.properties.createBlock.bind(this.properties);
  updateBlock = this.properties.updateBlock.bind(this.properties);
  deleteBlock = this.properties.deleteBlock.bind(this.properties);
  listProperties = this.properties.listProperties.bind(this.properties);
  listPropertiesPaginated = this.properties.listPropertiesPaginated.bind(this.properties);
  getProperty = this.properties.getProperty.bind(this.properties);
  createProperty = this.properties.createProperty.bind(this.properties);
  updateProperty = this.properties.updateProperty.bind(this.properties);
  deleteProperty = this.properties.deleteProperty.bind(this.properties);
  bulkDeleteProperties = this.properties.bulkDeleteProperties.bind(this.properties);
  bulkVerifyProperties = this.properties.bulkVerifyProperties.bind(this.properties);
  bulkRejectProperties = this.properties.bulkRejectProperties.bind(this.properties);
  getOrCreateAutoProperty = this.properties.getOrCreateAutoProperty.bind(this.properties);
  listIngestionBatches = this.properties.listIngestionBatches.bind(this.properties);
  getIngestionBatch = this.properties.getIngestionBatch.bind(this.properties);
  createIngestionBatch = this.properties.createIngestionBatch.bind(this.properties);
  updateIngestionBatch = this.properties.updateIngestionBatch.bind(this.properties);
  listGeocodedProperties = this.properties.listGeocodedProperties.bind(this.properties);
  updatePropertyGeodata = this.properties.updatePropertyGeodata.bind(this.properties);
  getPropertyRiskData = this.properties.getPropertyRiskData.bind(this.properties);

  listCertificates = this.certificates.listCertificates.bind(this.certificates);
  listCertificatesCursor = this.certificates.listCertificatesCursor.bind(this.certificates);
  listCertificatesPaginated = this.certificates.listCertificatesPaginated.bind(this.certificates);
  getCertificate = this.certificates.getCertificate.bind(this.certificates);
  createCertificate = this.certificates.createCertificate.bind(this.certificates);
  updateCertificate = this.certificates.updateCertificate.bind(this.certificates);
  findAndFailStuckCertificates = this.certificates.findAndFailStuckCertificates.bind(this.certificates);
  deleteCertificate = this.certificates.deleteCertificate.bind(this.certificates);
  getExtractionByCertificate = this.certificates.getExtractionByCertificate.bind(this.certificates);
  createExtraction = this.certificates.createExtraction.bind(this.certificates);
  listCertificateVersions = this.certificates.listCertificateVersions.bind(this.certificates);
  getCertificateVersion = this.certificates.getCertificateVersion.bind(this.certificates);
  createCertificateVersion = this.certificates.createCertificateVersion.bind(this.certificates);
  supersedeCertificateVersion = this.certificates.supersedeCertificateVersion.bind(this.certificates);
  listAuditFieldChanges = this.certificates.listAuditFieldChanges.bind(this.certificates);
  createAuditFieldChange = this.certificates.createAuditFieldChange.bind(this.certificates);
  createAuditFieldChanges = this.certificates.createAuditFieldChanges.bind(this.certificates);
  listUkhdsExports = this.certificates.listUkhdsExports.bind(this.certificates);
  getUkhdsExport = this.certificates.getUkhdsExport.bind(this.certificates);
  createUkhdsExport = this.certificates.createUkhdsExport.bind(this.certificates);
  updateUkhdsExport = this.certificates.updateUkhdsExport.bind(this.certificates);
  listCalendarEvents = this.certificates.listCalendarEvents.bind(this.certificates);
  getCalendarEvent = this.certificates.getCalendarEvent.bind(this.certificates);
  createCalendarEvent = this.certificates.createCalendarEvent.bind(this.certificates);
  updateCalendarEvent = this.certificates.updateCalendarEvent.bind(this.certificates);
  deleteCalendarEvent = this.certificates.deleteCalendarEvent.bind(this.certificates);
  getUpcomingEvents = this.certificates.getUpcomingEvents.bind(this.certificates);
  listDetectionPatterns = this.certificates.listDetectionPatterns.bind(this.certificates);
  getDetectionPattern = this.certificates.getDetectionPattern.bind(this.certificates);
  createDetectionPattern = this.certificates.createDetectionPattern.bind(this.certificates);
  updateDetectionPattern = this.certificates.updateDetectionPattern.bind(this.certificates);
  deleteDetectionPattern = this.certificates.deleteDetectionPattern.bind(this.certificates);
  listOutcomeRules = this.certificates.listOutcomeRules.bind(this.certificates);
  getOutcomeRule = this.certificates.getOutcomeRule.bind(this.certificates);
  createOutcomeRule = this.certificates.createOutcomeRule.bind(this.certificates);
  updateOutcomeRule = this.certificates.updateOutcomeRule.bind(this.certificates);
  deleteOutcomeRule = this.certificates.deleteOutcomeRule.bind(this.certificates);
  listGasApplianceRecords = this.certificates.listGasApplianceRecords.bind(this.certificates);
  createGasApplianceRecord = this.certificates.createGasApplianceRecord.bind(this.certificates);
  bulkCreateGasApplianceRecords = this.certificates.bulkCreateGasApplianceRecords.bind(this.certificates);
  listElectricalCircuitRecords = this.certificates.listElectricalCircuitRecords.bind(this.certificates);
  createElectricalCircuitRecord = this.certificates.createElectricalCircuitRecord.bind(this.certificates);
  bulkCreateElectricalCircuitRecords = this.certificates.bulkCreateElectricalCircuitRecords.bind(this.certificates);
  listFireSystemRecords = this.certificates.listFireSystemRecords.bind(this.certificates);
  createFireSystemRecord = this.certificates.createFireSystemRecord.bind(this.certificates);
  bulkCreateFireSystemRecords = this.certificates.bulkCreateFireSystemRecords.bind(this.certificates);
  listAsbestosSurveyRecords = this.certificates.listAsbestosSurveyRecords.bind(this.certificates);
  createAsbestosSurveyRecord = this.certificates.createAsbestosSurveyRecord.bind(this.certificates);
  bulkCreateAsbestosSurveyRecords = this.certificates.bulkCreateAsbestosSurveyRecords.bind(this.certificates);
  listWaterTemperatureRecords = this.certificates.listWaterTemperatureRecords.bind(this.certificates);
  createWaterTemperatureRecord = this.certificates.createWaterTemperatureRecord.bind(this.certificates);
  bulkCreateWaterTemperatureRecords = this.certificates.bulkCreateWaterTemperatureRecords.bind(this.certificates);

  listRemedialActions = this.remedials.listRemedialActions.bind(this.remedials);
  listRemedialActionsPaginated = this.remedials.listRemedialActionsPaginated.bind(this.remedials);
  getRemedialAction = this.remedials.getRemedialAction.bind(this.remedials);
  createRemedialAction = this.remedials.createRemedialAction.bind(this.remedials);
  updateRemedialAction = this.remedials.updateRemedialAction.bind(this.remedials);

  listContractors = this.contractors.listContractors.bind(this.contractors);
  getContractor = this.contractors.getContractor.bind(this.contractors);
  createContractor = this.contractors.createContractor.bind(this.contractors);
  updateContractor = this.contractors.updateContractor.bind(this.contractors);
  updateContractorStatus = this.contractors.updateContractorStatus.bind(this.contractors);
  bulkApproveContractors = this.contractors.bulkApproveContractors.bind(this.contractors);
  bulkRejectContractors = this.contractors.bulkRejectContractors.bind(this.contractors);
  listContractorCertifications = this.contractors.listContractorCertifications.bind(this.contractors);
  getContractorCertification = this.contractors.getContractorCertification.bind(this.contractors);
  createContractorCertification = this.contractors.createContractorCertification.bind(this.contractors);
  updateContractorCertification = this.contractors.updateContractorCertification.bind(this.contractors);
  deleteContractorCertification = this.contractors.deleteContractorCertification.bind(this.contractors);
  listContractorVerificationHistory = this.contractors.listContractorVerificationHistory.bind(this.contractors);
  createContractorVerificationHistory = this.contractors.createContractorVerificationHistory.bind(this.contractors);
  listContractorAlerts = this.contractors.listContractorAlerts.bind(this.contractors);
  getContractorAlert = this.contractors.getContractorAlert.bind(this.contractors);
  createContractorAlert = this.contractors.createContractorAlert.bind(this.contractors);
  updateContractorAlert = this.contractors.updateContractorAlert.bind(this.contractors);
  listContractorAssignments = this.contractors.listContractorAssignments.bind(this.contractors);
  getContractorAssignment = this.contractors.getContractorAssignment.bind(this.contractors);
  createContractorAssignment = this.contractors.createContractorAssignment.bind(this.contractors);
  updateContractorAssignment = this.contractors.updateContractorAssignment.bind(this.contractors);
  listStaffMembers = this.contractors.listStaffMembers.bind(this.contractors);
  getStaffMember = this.contractors.getStaffMember.bind(this.contractors);
  createStaffMember = this.contractors.createStaffMember.bind(this.contractors);
  updateStaffMember = this.contractors.updateStaffMember.bind(this.contractors);
  deleteStaffMember = this.contractors.deleteStaffMember.bind(this.contractors);
  bulkCreateStaffMembers = this.contractors.bulkCreateStaffMembers.bind(this.contractors);

  listComplianceStreams = this.configuration.listComplianceStreams.bind(this.configuration);
  getComplianceStream = this.configuration.getComplianceStream.bind(this.configuration);
  getComplianceStreamByCode = this.configuration.getComplianceStreamByCode.bind(this.configuration);
  createComplianceStream = this.configuration.createComplianceStream.bind(this.configuration);
  updateComplianceStream = this.configuration.updateComplianceStream.bind(this.configuration);
  deleteComplianceStream = this.configuration.deleteComplianceStream.bind(this.configuration);
  listCertificateTypes = this.configuration.listCertificateTypes.bind(this.configuration);
  getCertificateType = this.configuration.getCertificateType.bind(this.configuration);
  getCertificateTypeByCode = this.configuration.getCertificateTypeByCode.bind(this.configuration);
  createCertificateType = this.configuration.createCertificateType.bind(this.configuration);
  updateCertificateType = this.configuration.updateCertificateType.bind(this.configuration);
  deleteCertificateType = this.configuration.deleteCertificateType.bind(this.configuration);
  listClassificationCodes = this.configuration.listClassificationCodes.bind(this.configuration);
  getClassificationCode = this.configuration.getClassificationCode.bind(this.configuration);
  getClassificationCodeByCode = this.configuration.getClassificationCodeByCode.bind(this.configuration);
  createClassificationCode = this.configuration.createClassificationCode.bind(this.configuration);
  updateClassificationCode = this.configuration.updateClassificationCode.bind(this.configuration);
  deleteClassificationCode = this.configuration.deleteClassificationCode.bind(this.configuration);
  listExtractionSchemas = this.configuration.listExtractionSchemas.bind(this.configuration);
  getExtractionSchema = this.configuration.getExtractionSchema.bind(this.configuration);
  createExtractionSchema = this.configuration.createExtractionSchema.bind(this.configuration);
  updateExtractionSchema = this.configuration.updateExtractionSchema.bind(this.configuration);
  deleteExtractionSchema = this.configuration.deleteExtractionSchema.bind(this.configuration);
  listComplianceRules = this.configuration.listComplianceRules.bind(this.configuration);
  getComplianceRule = this.configuration.getComplianceRule.bind(this.configuration);
  createComplianceRule = this.configuration.createComplianceRule.bind(this.configuration);
  updateComplianceRule = this.configuration.updateComplianceRule.bind(this.configuration);
  deleteComplianceRule = this.configuration.deleteComplianceRule.bind(this.configuration);
  listNormalisationRules = this.configuration.listNormalisationRules.bind(this.configuration);
  getNormalisationRule = this.configuration.getNormalisationRule.bind(this.configuration);
  createNormalisationRule = this.configuration.createNormalisationRule.bind(this.configuration);
  updateNormalisationRule = this.configuration.updateNormalisationRule.bind(this.configuration);
  deleteNormalisationRule = this.configuration.deleteNormalisationRule.bind(this.configuration);

  listComponentTypes = this.components.listComponentTypes.bind(this.components);
  getComponentType = this.components.getComponentType.bind(this.components);
  createComponentType = this.components.createComponentType.bind(this.components);
  updateComponentType = this.components.updateComponentType.bind(this.components);
  deleteComponentType = this.components.deleteComponentType.bind(this.components);
  listSpaces = this.components.listSpaces.bind(this.components);
  getSpace = this.components.getSpace.bind(this.components);
  createSpace = this.components.createSpace.bind(this.components);
  updateSpace = this.components.updateSpace.bind(this.components);
  deleteSpace = this.components.deleteSpace.bind(this.components);
  listComponents = this.components.listComponents.bind(this.components);
  getComponent = this.components.getComponent.bind(this.components);
  createComponent = this.components.createComponent.bind(this.components);
  updateComponent = this.components.updateComponent.bind(this.components);
  deleteComponent = this.components.deleteComponent.bind(this.components);
  bulkCreateComponents = this.components.bulkCreateComponents.bind(this.components);
  listComponentCertificates = this.components.listComponentCertificates.bind(this.components);
  createComponentCertificate = this.components.createComponentCertificate.bind(this.components);
  deleteComponentCertificate = this.components.deleteComponentCertificate.bind(this.components);
  listDataImports = this.components.listDataImports.bind(this.components);
  getDataImport = this.components.getDataImport.bind(this.components);
  createDataImport = this.components.createDataImport.bind(this.components);
  updateDataImport = this.components.updateDataImport.bind(this.components);
  deleteDataImport = this.components.deleteDataImport.bind(this.components);
  listDataImportRows = this.components.listDataImportRows.bind(this.components);
  createDataImportRow = this.components.createDataImportRow.bind(this.components);
  bulkCreateDataImportRows = this.components.bulkCreateDataImportRows.bind(this.components);
  updateDataImportRow = this.components.updateDataImportRow.bind(this.components);
  getDataImportRowCounts = this.components.getDataImportRowCounts.bind(this.components);

  listApiLogs = this.api.listApiLogs.bind(this.api);
  createApiLog = this.api.createApiLog.bind(this.api);
  getApiLogStats = this.api.getApiLogStats.bind(this.api);
  listApiMetrics = this.api.listApiMetrics.bind(this.api);
  getOrCreateApiMetric = this.api.getOrCreateApiMetric.bind(this.api);
  updateApiMetric = this.api.updateApiMetric.bind(this.api);
  listWebhookEndpoints = this.api.listWebhookEndpoints.bind(this.api);
  getWebhookEndpoint = this.api.getWebhookEndpoint.bind(this.api);
  createWebhookEndpoint = this.api.createWebhookEndpoint.bind(this.api);
  updateWebhookEndpoint = this.api.updateWebhookEndpoint.bind(this.api);
  deleteWebhookEndpoint = this.api.deleteWebhookEndpoint.bind(this.api);
  getActiveWebhooksForEvent = this.api.getActiveWebhooksForEvent.bind(this.api);
  listWebhookEvents = this.api.listWebhookEvents.bind(this.api);
  createWebhookEvent = this.api.createWebhookEvent.bind(this.api);
  markWebhookEventProcessed = this.api.markWebhookEventProcessed.bind(this.api);
  getPendingWebhookEvents = this.api.getPendingWebhookEvents.bind(this.api);
  listWebhookDeliveries = this.api.listWebhookDeliveries.bind(this.api);
  createWebhookDelivery = this.api.createWebhookDelivery.bind(this.api);
  updateWebhookDelivery = this.api.updateWebhookDelivery.bind(this.api);
  listIncomingWebhookLogs = this.api.listIncomingWebhookLogs.bind(this.api);
  createIncomingWebhookLog = this.api.createIncomingWebhookLog.bind(this.api);
  updateIncomingWebhookLog = this.api.updateIncomingWebhookLog.bind(this.api);
  listApiKeys = this.api.listApiKeys.bind(this.api);
  getApiKey = this.api.getApiKey.bind(this.api);
  getApiKeyByPrefix = this.api.getApiKeyByPrefix.bind(this.api);
  createApiKey = this.api.createApiKey.bind(this.api);
  updateApiKey = this.api.updateApiKey.bind(this.api);
  deleteApiKey = this.api.deleteApiKey.bind(this.api);
  listApiClients = this.api.listApiClients.bind(this.api);
  getApiClient = this.api.getApiClient.bind(this.api);
  getApiClientByKey = this.api.getApiClientByKey.bind(this.api);
  createApiClient = this.api.createApiClient.bind(this.api);
  updateApiClient = this.api.updateApiClient.bind(this.api);
  deleteApiClient = this.api.deleteApiClient.bind(this.api);
  incrementApiClientUsage = this.api.incrementApiClientUsage.bind(this.api);
  listUploadSessions = this.api.listUploadSessions.bind(this.api);
  getUploadSession = this.api.getUploadSession.bind(this.api);
  getUploadSessionByIdempotencyKey = this.api.getUploadSessionByIdempotencyKey.bind(this.api);
  createUploadSession = this.api.createUploadSession.bind(this.api);
  updateUploadSession = this.api.updateUploadSession.bind(this.api);
  cleanupExpiredUploadSessions = this.api.cleanupExpiredUploadSessions.bind(this.api);
  listIngestionJobs = this.api.listIngestionJobs.bind(this.api);
  listAllIngestionJobs = this.api.listAllIngestionJobs.bind(this.api);
  getIngestionJob = this.api.getIngestionJob.bind(this.api);
  getIngestionJobByIdempotencyKey = this.api.getIngestionJobByIdempotencyKey.bind(this.api);
  createIngestionJob = this.api.createIngestionJob.bind(this.api);
  updateIngestionJob = this.api.updateIngestionJob.bind(this.api);
  getNextPendingIngestionJob = this.api.getNextPendingIngestionJob.bind(this.api);
  deleteIngestionJobsByChannel = this.api.deleteIngestionJobsByChannel.bind(this.api);
  getIngestionStats = this.api.getIngestionStats.bind(this.api);
  checkAndIncrementRateLimit = this.api.checkAndIncrementRateLimit.bind(this.api);
  cleanupExpiredRateLimits = this.api.cleanupExpiredRateLimits.bind(this.api);
  listVideos = this.api.listVideos.bind(this.api);
  getVideo = this.api.getVideo.bind(this.api);
  createVideo = this.api.createVideo.bind(this.api);
  updateVideo = this.api.updateVideo.bind(this.api);
  deleteVideo = this.api.deleteVideo.bind(this.api);
  incrementVideoView = this.api.incrementVideoView.bind(this.api);
  incrementVideoDownload = this.api.incrementVideoDownload.bind(this.api);
  listAiSuggestions = this.api.listAiSuggestions.bind(this.api);
  getAiSuggestion = this.api.getAiSuggestion.bind(this.api);
  getAiSuggestionByKey = this.api.getAiSuggestionByKey.bind(this.api);
  createAiSuggestion = this.api.createAiSuggestion.bind(this.api);
  updateAiSuggestion = this.api.updateAiSuggestion.bind(this.api);
  deleteAiSuggestion = this.api.deleteAiSuggestion.bind(this.api);
  dismissAiSuggestion = this.api.dismissAiSuggestion.bind(this.api);
  resolveAiSuggestion = this.api.resolveAiSuggestion.bind(this.api);
  autoResolveAiSuggestions = this.api.autoResolveAiSuggestions.bind(this.api);

  listFactorySettings = this.system.listFactorySettings.bind(this.system);
  getFactorySetting = this.system.getFactorySetting.bind(this.system);
  getFactorySettingValue = this.system.getFactorySettingValue.bind(this.system);
  createFactorySetting = this.system.createFactorySetting.bind(this.system);
  updateFactorySetting = this.system.updateFactorySetting.bind(this.system);
  createFactorySettingsAudit = this.system.createFactorySettingsAudit.bind(this.system);
  getSystemLogs = this.system.getSystemLogs.bind(this.system);
  recordAuditEvent = this.system.recordAuditEvent.bind(this.system);
  listAuditEvents = this.system.listAuditEvents.bind(this.system);
  getEntityAuditHistory = this.system.getEntityAuditHistory.bind(this.system);
  getEntityAuditHistoryForOrg = this.system.getEntityAuditHistoryForOrg.bind(this.system);
  listNavigationSections = this.system.listNavigationSections.bind(this.system);
  getNavigationSection = this.system.getNavigationSection.bind(this.system);
  createNavigationSection = this.system.createNavigationSection.bind(this.system);
  updateNavigationSection = this.system.updateNavigationSection.bind(this.system);
  deleteNavigationSection = this.system.deleteNavigationSection.bind(this.system);
  listNavigationItems = this.system.listNavigationItems.bind(this.system);
  getNavigationItem = this.system.getNavigationItem.bind(this.system);
  createNavigationItem = this.system.createNavigationItem.bind(this.system);
  updateNavigationItem = this.system.updateNavigationItem.bind(this.system);
  deleteNavigationItem = this.system.deleteNavigationItem.bind(this.system);
  getNavigationWithItems = this.system.getNavigationWithItems.bind(this.system);
  listNavigationItemsWithRoles = this.system.listNavigationItemsWithRoles.bind(this.system);
  getNavigationItemRoles = this.system.getNavigationItemRoles.bind(this.system);
  setNavigationItemRoles = this.system.setNavigationItemRoles.bind(this.system);
  listIconRegistry = this.system.listIconRegistry.bind(this.system);
  createIconRegistryEntry = this.system.createIconRegistryEntry.bind(this.system);
  listHazardCases = this.system.listHazardCases.bind(this.system);
  getHazardCase = this.system.getHazardCase.bind(this.system);
  createHazardCase = this.system.createHazardCase.bind(this.system);
  updateHazardCase = this.system.updateHazardCase.bind(this.system);
  listHazardActions = this.system.listHazardActions.bind(this.system);
  createHazardAction = this.system.createHazardAction.bind(this.system);
  updateHazardAction = this.system.updateHazardAction.bind(this.system);
  listTenantCommunications = this.system.listTenantCommunications.bind(this.system);
  createTenantCommunication = this.system.createTenantCommunication.bind(this.system);
  listHouseholds = this.system.listHouseholds.bind(this.system);
  getHousehold = this.system.getHousehold.bind(this.system);
  createHousehold = this.system.createHousehold.bind(this.system);
  updateHousehold = this.system.updateHousehold.bind(this.system);
  listTenants = this.system.listTenants.bind(this.system);
  getTenant = this.system.getTenant.bind(this.system);
  createTenant = this.system.createTenant.bind(this.system);
  updateTenant = this.system.updateTenant.bind(this.system);
  listServiceRequests = this.system.listServiceRequests.bind(this.system);
  getServiceRequest = this.system.getServiceRequest.bind(this.system);
  createServiceRequest = this.system.createServiceRequest.bind(this.system);
  updateServiceRequest = this.system.updateServiceRequest.bind(this.system);
  listTsmMeasures = this.system.listTsmMeasures.bind(this.system);
  getTsmMeasure = this.system.getTsmMeasure.bind(this.system);
  createTsmMeasure = this.system.createTsmMeasure.bind(this.system);
  listTsmSnapshots = this.system.listTsmSnapshots.bind(this.system);
  createTsmSnapshot = this.system.createTsmSnapshot.bind(this.system);
  listBuildingSafetyProfiles = this.system.listBuildingSafetyProfiles.bind(this.system);
  getBuildingSafetyProfile = this.system.getBuildingSafetyProfile.bind(this.system);
  getBuildingSafetyProfileByBlockId = this.system.getBuildingSafetyProfileByBlockId.bind(this.system);
  createBuildingSafetyProfile = this.system.createBuildingSafetyProfile.bind(this.system);
  updateBuildingSafetyProfile = this.system.updateBuildingSafetyProfile.bind(this.system);
  listSafetyCaseReviews = this.system.listSafetyCaseReviews.bind(this.system);
  createSafetyCaseReview = this.system.createSafetyCaseReview.bind(this.system);
  listMandatoryOccurrenceReports = this.system.listMandatoryOccurrenceReports.bind(this.system);
  getMandatoryOccurrenceReport = this.system.getMandatoryOccurrenceReport.bind(this.system);
  createMandatoryOccurrenceReport = this.system.createMandatoryOccurrenceReport.bind(this.system);
  updateMandatoryOccurrenceReport = this.system.updateMandatoryOccurrenceReport.bind(this.system);
}

export const storage = new DatabaseStorage();

export type {
  IStorage,
  IUsersStorage,
  IPropertiesStorage,
  ICertificatesStorage,
  IRemedialsStorage,
  IContractorsStorage,
  IConfigurationStorage,
  IComponentsStorage,
  IApiStorage,
  ISystemStorage
} from "./interfaces";
